<?php
/**
 * @author MageDad Team
 * @copyright Copyright (c) 2023 Magedad (https://www.magedad.com)
 * @package Magento 2 Admin ChatBot
 */

use Magento\Framework\Escaper;

/**
 * @var $block MageDad\AdminBot\Block\Adminhtml\ChatBot
 * @var $escaper Escaper
 */
?>

<?php if ($block->isAllowed()): ?>
<div class="fabs md-chatbox" id="md-chatbox">
    <div class="chat">
        <div class="chat-header">
            <div class="chat-option">
                <div class="header-img">
                    <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('MageDad_AdminBot::img/bot.png')); ?>"/>
                </div>
                <span id="chat-head"><?= /* @noEscape */ __('Admin Chatbot') ?></span>
                <span id="chat-help" class="chat-help">
                    <div class="admin__field-tooltip tooltip">
                        <a href="javascript:void(0);" title="<?= /* @noEscape */ __('All shortcuts') ?>"
                           class="admin__field-tooltip-action action-help">
                            <span><?= /* @noEscape */ __('All shortcuts') ?></span>
                        </a>
                    </div>
                </span>
            </div>
        </div>
        <div id="chat-fullscreen" class="chat-converse">
            <span class="chat-msg-item chat-msg-item-admin">
                <div class="chat-avatar">
                    <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('MageDad_AdminBot::img/bot.png')); ?>">
                </div>
                <div><?= /* @noEscape */ __('Hi, How can I help you?') ?></div>
            </span>
            <span class="chat-msg-item">
                <ul class="tags">
                    <?php foreach ($block->getPredefinedWords() as $key => $word): ?>
                        <li class="auto-suggest"><?= /* @noEscape */ $word ?></li>
                    <?php endforeach; ?>
                </ul>
            </span>
        </div>
        <div class="fab-field">
            <form>
                <select name="search-type" id="search-type">
                    <option value="">Select</option>
                    <?php foreach ($block->getPredefinedWords() as $key => $word): ?>
                        <option class="auto-suggest"><?= /* @noEscape */ $word ?></option>
                    <?php endforeach; ?>
                </select>
                <input type="text" placeholder="Type something here.." required  class="chat-field chat-message">
                <button type="submit" class="send-message"><i class="zmdi zmdi-mail-send"></i></button>
            </form>
        </div>
    </div>
    <a id="prime" class="fab"><i class="prime zmdi zmdi-comment-outline"></i></a>
</div>
<div id="chatbot-shortcut-modal">
    <div id="chatbot-shortcut-modal-content"></div>
</div>
<script type="text/x-magento-init">
  {
    "#md-chatbox": {
      "chatBot": {
        "url": "<?= /* @noEscape */ $block->getUrl('adminhtml/index/request'); ?>",
        "shortcutUrl": "<?= /* @noEscape */ $block->getUrl('adminhtml/index/shortcut'); ?>",
        "botImage": "<?= /* @noEscape */ $block->getViewFileUrl('MageDad_AdminBot::img/bot.png'); ?>"
      }
    }
  }
</script>
<?php endif; ?>
